stages:
  - test
  - deploy

services:
  - name: mongo:7
    alias: mongo

variables:
  PYTHONPATH: $CI_PROJECT_DIR
  UV_CACHE_DIR: $CI_PROJECT_DIR/.uv

before_script:
  - python3 -m venv .venv
  - source .venv/bin/activate
  - pip install uv || pip install --upgrade pip && pip install uv
  - uv sync
  - echo "✅ ENV=$ENV | CI=$CI | PYTHONPATH=$PYTHONPATH"

test:
  stage: test
  script:
    - make load
    - make test
  only:
    - main
    - merge_requests

deploy:
  stage: deploy
  script:
    - 'echo "🚀 CI Deploy: make prod_deploy"'
    - make prod_deploy ENV=PROD
  only:
    - main
