stages:
  - run

services:
  - name: mongo:7
    alias: mongo

variables:
  ENV: test
  MONGO_URI: mongodb://mongo:27017
  PYTHONPATH: $CI_PROJECT_DIR

before_script:
  - export PATH="$HOME/.local/bin:$PATH"
  - export PYTHONPATH="$(pwd)" 
  - make uv

run:
  stage: run
  script:
    - echo "🚀 Running make all"
    - make all
  only:
    - main
